{
 "title": "IOT Dashboard",
 "tags": [
  "prometheus",
  "influxdb",
  "graphite",
  "mixed"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "(ecobee_temperature_actual)", "legendFormat": "{{sensor_name}}" },
    {
     "target": "alias(sensor.mysensor.temp_f, 'Basement')"
    },
    {
     "alias": "Downstairs E",
     "measurement": "Environment",
     "query": "SELECT mean(\"ambient_f\") FROM \"Environment\" WHERE (\"data\" =~ /^$data$/) AND $timeFilter GROUP BY time($__interval), \"data\"",
     "select": [
      [
       { "params": [ "ambient_f" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "data", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "data", "operator": "=", "value": "Temperature" }
     ]
    },
    {
     "alias": "Upstairs E",
     "measurement": "Environment2",
     "query": "SELECT mean(\"value\") FROM \"Environment\" WHERE (\"data\" =~ /^$data$/) AND $timeFilter GROUP BY time($__interval), \"data\"",
     "select": [
      [
       { "params": [ "ambient_f" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "data", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "data", "operator": "=", "value": "Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    { "expr": "(ecobee_temperature_actual)", "legendFormat": "{{sensor_name}}" },
    {
     "target": "alias(sensor.mysensor.temp_f, 'Basement')"
    },
    {
     "alias": "Downstairs E",
     "measurement": "Environment",
     "query": "SELECT mean(\"ambient_f\") FROM \"Environment\" WHERE (\"data\" =~ /^$data$/) AND $timeFilter GROUP BY time($__interval), \"data\"",
     "select": [
      [
       { "params": [ "ambient_f" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "data", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "data", "operator": "=", "value": "Temperature" }
     ]
    },
    {
     "alias": "Upstairs E",
     "measurement": "Environment2",
     "query": "SELECT mean(\"value\") FROM \"Environment\" WHERE (\"data\" =~ /^$data$/) AND $timeFilter GROUP BY time($__interval), \"data\"",
     "select": [
      [
       { "params": [ "ambient_f" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "data", "operator": "=", "value": "Temperature" },
      { "condition": "AND", "key": "data", "operator": "=", "value": "Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "(ecobee_humidity)", "legendFormat": "{{sensor_name}}" },
    {
     "target": "alias(sensor.mysensor.humidity, 'Basement')"
    },
    { "expr": "dht_humidity", "legendFormat": "Attic" }
   ]
  },
  {
   "title": "Room Occupancy",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "(ecobee_occupancy)", "legendFormat": "{{sensor_name}}" }
   ]
  },
  {
   "title": "Hue Lights",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hue_group_on{type=\"Room\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}