{
 "title": "ObsCon",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1>Lab env</h1></center>\n"
   }
  },
  {
   "title": "Jobs Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(up < 1)" }
   ]
  },
  {
   "title": "Hosts Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(ecobee_occupancy)" }
   ]
  },
  {
   "title": "Gateway Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"192.168.2.1\",replica=\"\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m]))))\n",
     "legendFormat": "CPU Idle"
    },
    {
     "expr": "min(node_filesystem_avail_bytes{instance=\"192.168.2.201:9100\"} /node_filesystem_size_bytes{instance=\"192.168.2.201:9100\"})",
     "legendFormat": "Min Space"
    },
    {
     "expr": "min(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "Min Memory"
    },
    { "aggregation": "max", "alias": "Datadog Agents Running", "metric": "datadog.agent.running" }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "topk(250,ts(\"kubernetes.pod_container.uptime\",cluster=\"grafana\"%20and%20nodename=\"minikube\"))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "<br /><center><h3>CPU</h3><center>\n"
   }
  },
  {
   "title": "Disk Free",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_avail_bytes /node_filesystem_size_bytes) by (mountpoint)\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "k8s CPU Usage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "mean",
     "filters": [
      { "key": "cluster=", "value": "se-demo-kit" },
      { "key": "namespace_name=", "value": "development" }
     ],
     "functions": [
      {
       "name": "topk",
       "parameters": [
        { "value": "20" }
       ]
      }
     ],
     "metric": "kubernetes.pod_container.cpu.usage_rate"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 7, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[2m])) by (device) > 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 5, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" },
    { "alias": "Datadog", "metric": "system.load.1" }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
     "legendFormat": "{{instance}}"
    },
    { "aggregation": "avg", "groupBy": [ "host" ], "metric": "system.mem.free" }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{error_level=\"ERROR\"}"
    }
   ]
  }
 ]
}