{
 "title": "Web app observability dashboard",
 "tags": [
  "prometheus",
  "loki",
  "web",
  "docker",
  "demo"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Webapp",
    "query": "{service=~ \"web_app_.+\"}"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "{kubernetes_namespace=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background: url('https://i.ibb.co/gmYD7BN/gearbg.jpg'); background-repeat: no-repeat; background-size: cover;\">\n   <img src=\"https://i.ibb.co/QJyKvjZ/1397119524.png\" style=\"width:100px\" />\n   <span style=\"font-size: 2.5em; color: black; -webkit-text-stroke: 2px black\">WidgetCo Industries - Web App Overview</span>\n</div>\n"
   },
   "content": "<div style=\"background: url('https://i.ibb.co/gmYD7BN/gearbg.jpg'); background-repeat: no-repeat; background-size: cover;\">\n   <img src=\"https://i.ibb.co/QJyKvjZ/1397119524.png\" style=\"width:100px\" />\n   <span style=\"font-size: 2.5em; color: black; -webkit-text-stroke: 2px black\">WidgetCo Industries - Web App Overview</span>\n</div>\n",
   "targets": [
    {
     "binOptions": {
      "bins": null
     },
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "limit": null,
      "partial": true
     },
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Concurrent webapp users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_http_requests{service=~\"[[service]]\",kubernetes_namespace=~\"[[environment]]\"}",
     "legendFormat": "{{service}}"
    },
    {}
   ]
  },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 } },
  {
   "title": "Current Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(web_http_requests{service=~\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "Error Rate (60s)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(web_http_5xx_errors[1m]) + rate(web_http_4xx_clients_errors[1m]) + rate(web_http_3xx_redirection[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Message Queue",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate({service=~\"[[service]]\"}[1s])) by (error_level)",
     "legendFormat": "{{error_level}}"
    }
   ]
  },
  {
   "title": "HTTP Error codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(web_http_5xx_errors[2s])) by (service)",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(web_http_4xx_clients_errors[10s])) by (service)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(web_http_3xx_redirection[10s])) by (service)",
     "legendFormat": "3XX"
    }
   ]
  },
  {
   "title": "HTTP Server Logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({service=~\"[[service]]\"}[1s])) by (error_level)"
    }
   ]
  },
  {
   "title": "Log Stream",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{service=~\"[[service]]\"}"
    }
   ]
  }
 ]
}